<a href="https://colab.research.google.com/github/adwaith-santhosh/ict_casestudy/blob/main/Data_acquisition_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

Task 1

Read the Population dataset from the CSV file.

Hint:

● Use the pandas library.

● Display the first five rows.

● Check the shape and data types.

In [15]:
data1=pd.read_csv('/content/population.csv')

In [4]:
data1.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [5]:
data1.shape

(25, 2)

Task 2

Read the GDP dataset from the Excel file.

Hint:

● Use the appropriate pandas function.

● Display column names and data types.

In [16]:
data2=pd.read_excel('/content/gdp.xlsx')
data2

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [7]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

Task 3

Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame.

In [17]:
data3=pd.read_json('/content/internet_users.json')
data=pd.DataFrame(data3)
data

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4

Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [18]:
data4=pd.read_xml('/content/literacy_rate.xml')
data4

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [11]:
pd.DataFrame(data4)

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 5

Explore each dataset.

Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [19]:
print('Number of rows and columns of population.csv:',data1.shape)
print('Number of rows and columns of gdp.xlsx:',data2.shape)
print('Number of rows and columns of internet_users.json:',data3.shape)
print('Number of rows and columns of literacy_rate.xml:',data4.shape)

Number of rows and columns of population.csv: (25, 2)
Number of rows and columns of gdp.xlsx: (25, 2)
Number of rows and columns of internet_users.json: (25, 2)
Number of rows and columns of literacy_rate.xml: (25, 2)

In [20]:
print('columns and datatype of population.csv:',data1.columns)
print('columns and datatype of gdp.xlsx:',data2.columns)
print('columns and datatype of internet_users.json:',data3.columns)
print('columns and datatype of literacy_rate.xml:',data4.columns)

columns of population.csv: Index(['country', 'population'], dtype='object')
columns of gdp.xlsx: Index(['Country', 'GDP'], dtype='object')
columns of internet_users.json: Index(['country', 'internet_users'], dtype='object')
columns of literacy_rate.xml: Index(['name', 'literacy_rate'], dtype='object')

In [30]:
print('Number of missing values in population.csv:\n',data1.isnull().sum())
print('Number of missing values in gdp.xlsx:\n',data2.isnull().sum())
print('Number of missing values in internet_users.json:\n',data3.isnull().sum())
print('Number of missing values in literacy_rate.xml:\n',data4.isnull().sum())

Number of missing values in population.csv:
 country       0
population    0
dtype: int64
Number of missing values in gdp.xlsx:
 Country    0
GDP        0
dtype: int64
Number of missing values in internet_users.json:
 country           0
internet_users    0
dtype: int64
Number of missing values in literacy_rate.xml:
 name             0
literacy_rate    0
dtype: int64

In [31]:
print('Number of duplicate records in population.csv:',data1.duplicated().sum())
print('Number of duplicate records in gdp.xlsx:',data2.duplicated().sum())
print('Number of duplicate records in internet_users.json:',data3.duplicated().sum())
print('Number of duplicate records in literacy_rate.xml:',data4.duplicated().sum())

Number of duplicate records in population.csv: 0
Number of duplicate records in gdp.xlsx: 0
Number of duplicate records in internet_users.json: 0
Number of duplicate records in literacy_rate.xml: 0

Task 6

Rename columns wherever necessary so that all datasets have a common
column name for merging.

Hint:

● Example: Country → country

In [32]:
data2.rename(columns={'Country':'country'},inplace=True)

In [33]:
data4.rename(columns={'name':'country'},inplace=True)

In [35]:
print(data1.columns)
print(data2.columns)
print(data3.columns)
print(data4.columns)

Index(['country', 'population'], dtype='object')
Index(['country', 'GDP'], dtype='object')
Index(['country', 'internet_users'], dtype='object')
Index(['country', 'literacy_rate'], dtype='object')

Task 7

Convert the required columns into appropriate numeric data types.

In [38]:
print(data1.dtypes)
print(data2.dtypes)
print(data3.dtypes)
print(data4.dtypes)

country       object
population     int64
dtype: object
country    object
GDP         int64
dtype: object
country           object
internet_users     int64
dtype: object
country           object
literacy_rate    float64
dtype: object

Task 8

Merge all four datasets into one DataFrame.

Hint:

● Use the common column (country)

● Choose an appropriate join method.

In [39]:
merged_data=pd.merge(data1,data2,on='country',how='inner')
merged_data=pd.merge(merged_data,data3,on='country',how='inner')
merged_data=pd.merge(merged_data,data4,on='country',how='inner')
merged_data

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

Task 9

Create the following calculated columns:

1. Internet Penetration (%)

2. GDP Per Capita

Hint:

Round the calculated values to two decimal places.

In [46]:
merged_data['Internet penetration(%)']=((merged_data['internet_users']/merged_data['population'])*100).round(2)
merged_data['GDP Per Capita']=(merged_data['GDP']/merged_data['population']).round(2)
merged_data

,country,population,GDP,internet_users,literacy_rate,Internet penetration(%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
6,France,65273511,3211000,62000000,99.0,94.98,0.05
7,Italy,60461826,2420000,56000000,99.0,92.62,0.04
8,Canada,38005238,2250000,36000000,99.0,94.72,0.06
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
11,Russia,145934462,2200000,125000000,99.7,85.65,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
13,Spain,46754778,1710000,44000000,98.6,94.11,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
18,South Africa,59308690,410000,43000000,95.0,72.50,0.01
19,Argentina,45195774,640000,41000000,99.1,90.72,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Sweden,10353442,650000,10100000,99.0,97.55,0.06
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09

Task 10

Create a SQLite database. Store the final merged dataset into a table named

‘country_statistics’

Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas.

In [47]:
import sqlite3 as sq

In [51]:
conn=sq.connect('country_statistics.db')
merged_data.to_sql('country_statistics',conn,if_exists='replace',index=False)
print('database created successfully')

database created successfully

Task 11

Verify that the data has been loaded successfully.

Hint:
Retrieve the first five records from the SQLite table.

In [53]:
query='SELECT * FROM country_statistics LIMIT 5;'
result=pd.read_sql(query,conn)
result

,country,population,GDP,internet_users,literacy_rate,Internet penetration(%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

Part E – Data Analysis Using Pandas

Answer the following questions using pandas.

1. List the Top 5 countries by GDP

In [57]:
q1=merged_data.sort_values(by='GDP',ascending=False).head()
q1[['country','GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

2. List the Top 5 countries by population.

In [58]:
q2=merged_data.sort_values(by='population',ascending=False).head()
q2[['country','population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

3. Calculate the average literacy rate.

In [61]:
q3=merged_data['literacy_rate'].mean()
print(q3)

97.248

4. List all countries having a literacy rate greater than 90%.

In [63]:
q4=merged_data[merged_data['literacy_rate']>90]
q4[['country','literacy_rate']]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

5. List all countries having an internet penetration greater than 70%.

In [64]:
q5=merged_data[merged_data['Internet penetration(%)']>70]
q5[['country','Internet penetration(%)']]

           country  Internet penetration(%)
0    United States                    94.26
1            China                    76.50
3            Japan                    93.77
4          Germany                    94.91
5   United Kingdom                    97.22
6           France                    94.98
7            Italy                    92.62
8           Canada                    94.72
9        Australia                    93.43
10          Brazil                    85.15
11          Russia                    85.65
12     South Korea                    96.56
13           Spain                    94.11
14          Mexico                    79.11
15       Indonesia                    77.51
16    Saudi Arabia                    97.66
17          Turkey                    81.81
18    South Africa                    72.50
19       Argentina                    90.72
20     Netherlands                    97.47
21     Switzerland                    98.21
22          Sweden                    97.55
23          Norway                    97.76
24       Singapore                    95.72

6. List the Top 5 countries by GDP per capita.

In [66]:
q6=merged_data.sort_values(by='GDP Per Capita',ascending=False).head()
q6[['country','GDP Per Capita']]

          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
24      Singapore            0.09
0   United States            0.09
9       Australia            0.07

7. Calculate the total population represented in the dataset.

In [68]:
q7=merged_data['population'].sum()
print(q7)

4720039725

8. Calculate the average internet penetration across all countries.

In [70]:
q8=merged_data['Internet penetration(%)'].mean()
print(q8)

89.6596

9. Identify the country having the highest number of internet users.

In [71]:
q9=merged_data.sort_values(by='internet_users',ascending=False).head(1)
q9

,country,population,GDP,internet_users,literacy_rate,Internet penetration(%),GDP Per Capita
1,China,1411778724,19230000,1080000000,97.2,76.5,0.01

10. Find the correlation between Literacy Rate and Internet Penetration.

In [75]:
correlation=merged_data['literacy_rate'].corr(merged_data["Internet penetration(%)"])
print(correlation)

0.77279756813985

Part F – Data Analysis Using SQL

Answer the following questions using SQLite queries.

11. Display the Top 5 countries by GDP.

In [80]:
q11='''SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5;'''
pd.read_sql(q11,conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

12. Find the average literacy rate.

In [81]:
q12='''SELECT AVG(literacy_rate) from country_statistics;  '''
pd.read_sql(q12,conn)

   AVG(literacy_rate)
0              97.248

13. Display all countries having literacy rate above 90%.

In [82]:
q13 = """SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90;"""

print(pd.read_sql(q13, conn))

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

14. Find the Top 5 countries with the highest internet penetration.

In [84]:
q14 = """
SELECT country, [Internet penetration(%)]
FROM country_statistics
ORDER BY [Internet penetration(%)] DESC
LIMIT 5;
"""

print(pd.read_sql(q14, conn))

        country  Internet penetration(%)
0   Switzerland                    98.21
1        Norway                    97.76
2  Saudi Arabia                    97.66
3        Sweden                    97.55
4   Netherlands                    97.47

15. Calculate the total population

In [85]:
q15 = """
SELECT SUM(population) AS total_population
FROM country_statistics;
"""

print(pd.read_sql(q15, conn))

   total_population
0        4720039725

16. Find the country with the highest GDP per capita.

In [86]:
q16 = """
SELECT country, [GDP Per Capita]
FROM country_statistics
ORDER BY [GDP Per Capita] DESC
LIMIT 1;
"""

print(pd.read_sql(q16, conn))

       country  GDP Per Capita
0  Switzerland            0.11

17. Export the final merged dataset as a CSV file.

In [87]:
query = "SELECT * FROM country_statistics;"

df = pd.read_sql(query, conn)

df.to_csv("country_statistics.csv", index=False)

print("CSV file exported successfully.")

CSV file exported successfully.

18 Sort the dataset in descending order of GDP per Capita and display the Top 10
countries.

In [88]:
query = """
SELECT *
FROM country_statistics
ORDER BY [GDP Per Capita] DESC
LIMIT 10;
"""

print(pd.read_sql(query, conn))

          country  population       GDP  internet_users  literacy_rate  \
0     Switzerland     8654622    940000         8500000           99.0
1          Norway     5421241    580000         5300000          100.0
2   United States   331002651  30500000       312000000           99.0
3       Singapore     5850342    530000         5600000           97.5
4       Australia    25687041   1880000        24000000           99.0
5     Netherlands    17441139   1150000        17000000           99.0
6         Germany    83240525   4744000        79000000           99.0
7  United Kingdom    67886011   3839000        66000000           99.0
8          Canada    38005238   2250000        36000000           99.0
9          Sweden    10353442    650000        10100000           99.0

   Internet penetration(%)  GDP Per Capita
0                    98.21            0.11
1                    97.76            0.11
2                    94.26            0.09
3                    95.72            0.09
4                    93.43            0.07
5                    97.47            0.07
6                    94.91            0.06
7                    97.22            0.06
8                    94.72            0.06
9                    97.55            0.06

Write a short summary (5–6 points) explaining your ETL process, including:

● Data sources used

● Data cleaning steps

● Transformations performed

● Database loading process

● Key insights obtained from the analysis

Data Sources Used: Collected data from four different file formats—CSV (Population), Excel (GDP), JSON (Internet Users), and XML (Literacy Rate).

Data Cleaning Steps: Standardized column names (e.g., Country → country), checked and corrected data types, removed inconsistencies, and ensured all datasets had a common key (country) for merging.

Transformations Performed: Merged all four datasets into a single DataFrame and created two new calculated columns: Internet Penetration (%) and GDP Per Capita.

Database Loading Process: Created a SQLite database (country_statistics.db) and loaded the final merged DataFrame into a table named country_statistics using Pandas' to_sql() method. Verified the data by retrieving the first five records.

Data Analysis: Performed analysis using both Pandas and SQLite queries to identify top countries by GDP and population, calculate averages and totals, determine GDP per capita, internet penetration, and analyze the relationship between literacy rate and internet usage.

Key Insights Obtained: Countries with higher GDP generally have higher GDP per capita and internet penetration. A positive correlation was observed between literacy rate and internet penetration, indicating that countries with better literacy tend to have greater internet access.